version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot npm"
    labels:
      - "dependencies"
    reviewers:
      - "dusthijsvdh"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot ac"
    labels:
      - "dependencies"
    reviewers:
      - "dusthijsvdh"
